default_install_hook_types: [pre-commit, pre-push]
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.96.1
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      stages: [pre-push]
