default_install_hook_types:
  - pre-commit
  - pre-push
repos:
  - hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
          - --hook-config=--use-standard-markers=true
        stages:
          - pre-push
    repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
  - hooks:
      - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.30.0
